# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAVK5li3qwN3Y1F2LLRQwZ97eZaO6SLn
"""

!pip freeze > requirements.txt